### ISSUE TITLE
Failure for lightcurves with gaps

### ISSUE THREAD

**Issue by philastrophist** [AstroVPK/kali#8]
I've run Kali with a reprocessed light curve from Smith+18 and it fails with error:

https://gist.github.com/philastrophist/02a1444ab8a51f29e37481f7b40650ea 
```
notice: kali tools have been set up.
/opt/conda/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:1628: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)
Traceback (most recent call last):
  File "/project/smith18_data/fit_carma.py", line 82, in <module>
    task.fit(lc)
  File "/home/kali/python/kali/carma.py", line 1048, in fit
    self.bestTheta
  File "/home/kali/python/kali/carma.py", line 1058, in bestTheta
    bestWalker = np.where(np.max(self.LnPosterior) == self.LnPosterior)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Is this because there are gaps? If so, then how does the SDSS lightcurve in your `guide/introduction.ipynb` work?

Thanks

**Comment by AstroVPK** [comment]
I'll try to take a look at it either later today or tomorrow - sorry, but
there's some personal stuff that's keeping me busy.

Vishal Kasliwal
Senior Deep Learning Software Engineer
Intel Corporation <https://www.intel.com/content/www/us/en/homepage.html>

**Comment by philastrophist** [comment]
Ok, thanks!

**Comment by philastrophist** [comment]
Ok, it runs now and returns some results! 

However, they look a bit weird: The psd doesn't really track the data that well and nor does the SF.
Have a look at the pdf in the gist if you can. Is it expected to be like this? I know that at the high freq end we're observationally limited so that could explain the PSD but not the SF! I'd been interested to know what you think... 
Thanks for your help
